### ISSUE TITLE
psram ID is not known

### ISSUE THREAD

**Issue by Tungraider** [sd2psx/firmware#11]
Hi sir

Well, after I updated the firmware version the board started to present this problem
"FATAL ERROR
PSRAM ID is not knowm Good die try to Power-cycle it if PSRAM is stuck in the API Mode"

I would like to know if there is a solution for this case please

**Comment by xyzz** [comment]
Can you show a picture of your pcb, with the psram chip markings (U4) visible?

**Comment by Tungraider** [comment]
![20230212_104217](https://user-images.githubusercontent.com/107059804/218314640-5d22a30d-c558-43b0-a081-e6e8fe82590f.jpg)

**Comment by xyzz** [comment]
I've just added more debug output, can you try the latest firmware and report back what it shows

**Comment by Tungraider** [comment]
![20230212_193547](https://user-images.githubusercontent.com/107059804/218341411-74073d40-bda6-40aa-a160-8eea113ef85a.jpg)

Now this message appears

**Comment by xyzz** [comment]
it sounds like either the psram chip is dead, or maybe there's a short somewhere on the lines connecting it to the rp2040

**Comment by Tungraider** [comment]
ok thanks for the feedback
