### ISSUE TITLE
bug report on New FW

### ISSUE THREAD

**Issue by hpx1984** [sd2psx/firmware#12]
1.Upgrade FW to the new one and some times got the error information as below , switch no response 
![image](https://user-images.githubusercontent.com/76941051/219997093-3214eabc-f2e1-47f7-a10f-2050a344076a.png)
![image](https://user-images.githubusercontent.com/76941051/219997123-48d98fe1-2a32-40c7-a143-3b3c34a0bf1a.png)

2. ps1 mode good working but PS2 mode couldn't detect the McmCard on PS2 
ensure the CIV file is correct because PS2 mode good working on old FW
re-programming to the old FW couldn't fix this problem 
any comment,sir?

**Comment by xyzz** [comment]
It sounds like a problem with the microsd, is it a genuine microsd card? can you try another?

- "cannot read memcard": it is returned when read 512 bytes from microsd fails (although maybe we could improve sd2psx by retrying the read)
- "... is corrupted": this is when the size of the underlying memory card image (CardX-Y.mcd) is not correct

So it sounds like the microsd is maybe dying, can you put it into pc and see if it works fine?

Regarding second issue, can you show output from UART port (either using USB debug firmware, or soldering wire to the UART header)?

**Comment by xyzz** [comment]
Closing since no response
