### ISSUE TITLE
Feature request: Automatic switching based on Game ID

### ISSUE THREAD

**Issue by moghingold** [sd2psx/firmware#13]
The following modified BIOS just got released for PS1 games: https://github.com/jdfr228/PS1-Disc-Based-Game-ID

Currently proprietary mods like the MemCard Pro and PS1 Digital are looking at integrating this functionality into their products to do various things. A good thing this could be used for on the SD2PSX would be auto-selecting the virtual memory card for PS1 games when used in a PS1 console.

Is this feasible based on how SD2PSX works? If so I think would be really cool if it could be supported!

**Comment by xyzz** [comment]
this is already implemented since https://github.com/sd2psx/firmware/pull/4 actually
