### ISSUE TITLE
Limited Memory Card 8 MB Size

### ISSUE THREAD

**Issue by elifasjvc** [sd2psx/firmware#18]
Hello, Sorry, but this is not really a problem but a suggestion.

Would it be possible to implement other memory card sizes, for example 128 MB?

I have a 128MB card with a lot of saved games on it and I wanted to move them to sd2psx.

Or is there any alternative for this operation?

If this is not the right place, I apologize and thank you for your attention.

Thank you very much for your work.

**Comment by xyzz** [comment]
Currently it is limited by the size of the PSRAM chip on the PCB. So it cannot be bigger unless the implementation of the emulation is changed in a major way. You can move your save data to different emulated cards/channels; eventually the idea is to have game-specific cards with autodetection, similar to how PS1 mode works with an ODE.

**Comment by elifasjvc** [comment]
Thanks.
