### ISSUE TITLE
Export and Open PS2 Saves on a PC?

### ISSUE THREAD

**Issue by YorkieFl** [sd2psx/firmware#20]
I note that PS1 memory cards created for the PS1 can be opened easily enough in something like MemcardRex but I am having trouble opening the .mcd files for the PS2 memory cards that are created.

Programs like PS2 Save Builder cannot open the files so I was wondering if there was an easy way to edit the saves or if we'd just have to use FreeMcBoot to paste saves we want to add from a usb stick to a created memory card

**Comment by xyzz** [comment]
You need a memory card manager that supports 512-byte blocks (without ECC). Most of PS2 tools work on 528 byte blocks. One option is MyMC Dual v3 - you can download it from https://www.ps2-home.com/forum/viewtopic.php?t=2876. Note that it has to be v3 - under the "OLDER VERSIONS" spoiler, the latest version doesn't work. You'll also have to rename the card from .mcd to .bin
