### ISSUE TITLE
PS2 memory card images aren't compatible with emulators/memory card editors

### ISSUE THREAD

**Issue by nzgamer41** [sd2psx/firmware#23]
As the title states, the PS2 images SD2PSX creates don't appear to be compatible with any other software/PS2 memory card image format. MyMC(and MyMC Plus) both can't open the image, with "Uncorrectable ECC error" messages, and PCSX2 sees the memory card as an unformatted PS1 memory card. Ideally intercompatibility would be nice, for things like moving saves over from real memory cards to emulators.

**Comment by xyzz** [comment]
See https://github.com/sd2psx/firmware/issues/20#issuecomment-1627599735
