### ISSUE TITLE
Boot的元器件标注是错的吧

### ISSUE THREAD

**Issue by mingrockyou** [sd2psx/firmware#30]
那个位置应该是一个按钮，标注的是一个排针

**Comment by xyzz** [comment]
- please write the question in english in the future
- to reduce bom in the latest revision there is no button anymore and the pads can be shorted with tweezers or a piece of wire (this is only needed if firmware corruption occurred due to bad flashing procedure etc)

**Comment by mingrockyou** [comment]
> * 以后请用英语写下问题
> * 为了在最新修订版中减少bom，不再有按钮，垫子可以用镊子或一根电线短路（仅当由于闪烁程序不好等导致固件损坏时才需要）

Thank you very much for your answer.
