### ISSUE TITLE
PS2 mode show 0 free and dis-connect

### ISSUE THREAD

**Issue by hpx1984** [sd2psx/firmware#9]
Hi Sir

ps1 mode working fine both of PS1 and ps2（can saw the card icon and game save icon）

ps2 mode
after installed CIV then ps2 can saw the memory card icon but it will dis-connect and loss the cark icon then will re-connect and show the card icon 
and some times can see the free size but when i copy the game save file to it would show failed and the card is 0 free size 

if you know the issue and know how to fix it please share the solution

**Comment by xyzz** [comment]
1) Check that the value of CIV is correct, it must be exact 8 bytes and a specific value that it has to match
2) Check that the card is making good contact with the PS2 slot, for 3d printed case the tolerance may cause it to not fully contact

**Comment by hpx1984** [comment]
thanks your speed up comment

i'm sure the contact is good ,because ps1 mode is working very very good ,
so it seems may problem on CIV
i'm used the value code start from 2c and end of 27 what found form google, i'm not sure if it is the correct CIV

**Comment by hpx1984** [comment]
i got another one civ , will test it end of this week and will update the result  to you

**Comment by uberyoji** [comment]
Civ must be binary. Not text file.
Use an hex editor to generate it.

**Comment by hpx1984** [comment]
some thing wrong on HW, replace U3 the problem was fixed 
many thanks your great project
